// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoAkaE9hv2D_jEXhdJrGOMlBpDypbIrDg',
    appId: '1:583964619394:web:e204f18f2e663a3ba7ba9b',
    messagingSenderId: '583964619394',
    projectId: 'todo-e50ad',
    authDomain: 'todo-e50ad.firebaseapp.com',
    storageBucket: 'todo-e50ad.appspot.com',
    measurementId: 'G-XCMJX75RRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRdP2omcKiiwD7sZCGe_1JKViiltZp78s',
    appId: '1:583964619394:android:24a11ba61c16dc7aa7ba9b',
    messagingSenderId: '583964619394',
    projectId: 'todo-e50ad',
    storageBucket: 'todo-e50ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO0M856TZd6uCcMZ7R6-nIYuGbw7ryoDY',
    appId: '1:583964619394:ios:add58c41e553cb4fa7ba9b',
    messagingSenderId: '583964619394',
    projectId: 'todo-e50ad',
    storageBucket: 'todo-e50ad.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO0M856TZd6uCcMZ7R6-nIYuGbw7ryoDY',
    appId: '1:583964619394:ios:ada0d1d44f9c8553a7ba9b',
    messagingSenderId: '583964619394',
    projectId: 'todo-e50ad',
    storageBucket: 'todo-e50ad.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
